yield_config: &yield_config
  name: yield
  model_config: ./config/prod/model_config_regression_yield_absolute_newview2.yaml

chaff_elevator_config: &chaff_elevator_config
  name: chaff_elevator
  model_config: ./config/prod/model_config_segmentation_chaff_elevator.yaml

chaff_hopper_config: &chaff_hopper_config
  name: chaff_hopper
  model_config: ./config/prod/model_config_segmentation_chaff_hopper.yaml

lodging_config: &lodging_config
  name: lodging
  model_config: ./config/prod/model_config_segmentation_lodging.yaml

load_test:
  num_run: 300
  input_size: [2048, 1024, 3]

deploy_configs:
  models: [*yield_config, *chaff_elevator_config, *chaff_hopper_config, *lodging_config]

