RUN_ENV: local #{aws, local}
RUN_MODE: inference #{train, inference}
BATCH_SIZE: 1
LEARNING_RATE: 0.0001
EPOCHS: 300
TRAIN_STEPS_PER_EPOCH: -1
VALID_STEPS_PER_EPOCH: -1
NUM_CLASSES: 2
LOAD_MODEL: true #if true, Load_Model_Directory must be specified too
# LOAD_MODEL_DIRECTORY: s3://transformers-sample/zoomlion-sample/test_miivii/lodging_model/model.hdf5/cp.hdf5
LOAD_MODEL_DIRECTORY: s3://landing-ml-job-runs/wheat_yield_lodging/fu/lodging_v06_resnet18_BZ8_LR1-4/run_001/checkpoints/epoch_0001/cp.hdf5
DIR_OUT: /workspace/output/  #directory on the ec2 host, to save output files from code
DATA_DIR: s3://landing-client-zoomlion/data-for-models/lodging/qinghai-0824-1002/data-v0.6_chronological


DATA_GENERATOR:
  OUTPUT_SHAPE: [512, 512]
  OUTPUT_IMAGE_CHANNELS: 3
  OUTPUT_IMAGE_TYPE: float32
  DROP_REMAINDER: false
  CACHE_DIR: cache
  NUM_PARALLEL_CALLS: 4
  REPEAT: True

TRANSFORM:
  RESIZE: [512, 512]

TRAINING_DATA_INFO:
  TRAIN_CSV_FILE: s3://landing-client-zoomlion/data-for-models/lodging/qinghai-0824-1002/data-v0.6_chronological/train.csv
  VALID_CSV_FILE: s3://landing-client-zoomlion/data-for-models/lodging/qinghai-0824-1002/data-v0.6_chronological/train.csv
  SPLIT: split
  SPLIT_TRAIN_VAL: train
  SPLIT_VALID_VAL: valid
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label


MODEL:
  LAYER_SIZE: 64
  LAYER_COUNT: 5
  BACKBONE: resnet18
  IS_BACKBONE_TRAINABLE: true
  MODEL_DIRECTORY: out
  CHECKPOINT_DIRECTORY: checkpoint
  LOG_DIRECTORY: log


EXPERIMENT:
  EXPERIMENT_NAME: ExperimentSegmentationUnet
  MODEL_NAME: ModelUnetSegmentation
  TRAIN_TRANSFORM: TransformSegmentation
  TRAIN_GENERATOR: GeneratorSegmentation
  VALID_TRANSFORM: # If empty, use TRAIN_TRANSFORM
  VALID_GENERATOR: # If empty, use TRAIN_GENERATOR
  NUM_PLOTS: 10


INFERENCE:
  INFERENCE_NAME: InferenceLodgingTRT # or InferenceLodgingTRT
  #FIXME: May want to consider move INFERENCE_CSV_FILE and INFERENCE_DATA_DIR out of INFERENCE. We may load model for continuous training.
  INFERENCE_CSV_FILE: s3://landing-client-zoomlion/data-for-models/lodging/qinghai-0824-1002/data-v0.6_chronological/train.csv
  INFERENCE_DATA_DIR: s3://landing-client-zoomlion/data-for-models/lodging/qinghai-0824-1002/data-v0.6_chronological
  VIDEO_PATH: s3://zoomlion-sample/wheat-lodging/lodgingwheat/106APPLE/IMG_6989.MOV
  SPLIT: split #Column name in the csv file
  SPLIT_VAL: valid # {valid, train, all}
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label
  NUM_PROCESS_IMAGE: 30000
  PRED_IMAGE_DIR: pred_image
  EVALUATE: False # Evaluate model on a dataset with ground truth; won't generate segmentation images.
  VISUALIZE: False
  PB_FILE_PATH: s3://zoomlion-sample/tmp_unet_lodging_model/frozen_model.pb # freeze model should be done on x86 platform
  TRT_ENGINE_PATH: ~/zoomlion-sample/tmp_unet_lodging_model/frozen_model.engine # engine should be created on xavier
  CREATE_ENGINE: False
  FP16_MODE: False
  INPUT_NAME: data
  OUTPUT_NAME: sigmoid/Sigmoid
  NUM_FRAMES: 100
  CONTOUR_AREA_THRESHOLD: 1000



LOCAL_OVERRIDE:
  DIR_OUT: ./out
  DATA_DIR:

GRU:
  JOB_NAME: lodging_v06_resnet18_BZ8_LR1-4_noload
  PROJECT_NAME: wheat_yield_lodging
  INSTANCE_TYPE: p3.2xlarge
  TIMEOUT: 96
