RUN_ENV: aws #{aws, local}
RUN_MODE: train #{train, inference}

BATCH_SIZE: 4
LEARNING_RATE: 0.0001
EPOCHS: 1000
TRAIN_STEPS_PER_EPOCH: -1
VALID_STEPS_PER_EPOCH: -1
NUM_CLASSES: 2
LOAD_MODEL: True  #if true, Load_Model_Directory must be specified too
# LOAD_MODEL_DIRECTORY: s3://landing-ml-job-runs/wheat_yield_chaff/trosenflanz/elevator_chaff/run_013/checkpoints/epoch_0005/cp.hdf5 #inference
# LOAD_MODEL_DIRECTORY: s3://landing-ml-job-runs/wheat_yield_chaff/trosenflanz/wheat_chaff_segmentation/run_014/checkpoints/epoch_0007/cp.hdf5 #for training, pretrained on older data
LOAD_MODEL_DIRECTORY: s3://landing-ml-job-runs/wheat_yield_chaff/yuanzhedong/chaff_hopper_data_v04/run_005/checkpoints/epoch_0005/cp.hdf5
DIR_OUT: /workspace/output/
DATA_DIR: s3://landing-client-zoomlion/data-for-models/chaff-hopper/qinghai-0824-1002/data-v0.4_chronological/
# DATA_DIR: model.hdf5

DATA_GENERATOR:
  OUTPUT_SHAPE: [512, 512]
  OUTPUT_IMAGE_CHANNELS: 3
  OUTPUT_IMAGE_TYPE: float32
  DROP_REMAINDER: false
  CACHE_DIR: cache
  NUM_PARALLEL_CALLS: 4
  REPEAT: true

TRANSFORM:
  RESIZE: [512, 512]

TRAINING_DATA_INFO:
  TRAIN_CSV_FILE: s3://landing-client-zoomlion/data-for-models/chaff-hopper/qinghai-0824-1002/data-v0.4_chronological/train.csv
  VALID_CSV_FILE: s3://landing-client-zoomlion/data-for-models/chaff-hopper/qinghai-0824-1002/data-v0.4_chronological/train.csv
  SPLIT: split
  SPLIT_TRAIN_VAL: train
  SPLIT_VALID_VAL: valid
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label


MODEL:
  LAYER_SIZE: 64 #can be a list
  LAYER_COUNT: 5 #ignored if LAYER_SIZE  is list
  #BACKBONE: efficientnetb0  #{any backbone from https://github.com/qubvel/segmentation_models#models-and-backbones} for Unet
                            # nobackbone or mobilenet-v2
  BACKBONE: resnet18
  IS_BACKBONE_TRAINABLE: true

EXPERIMENT:
  EXPERIMENT_NAME: ExperimentSegmentationUnet
  MODEL_NAME: ModelUnetSegmentation
  TRAIN_TRANSFORM: TransformSegmentation
  TRAIN_GENERATOR: GeneratorSegmentation
  VALID_TRANSFORM: # If empty, use TRAIN_TRANSFORM
  VALID_GENERATOR: # If empty, use TRAIN_GENERATOR
  NUM_PLOTS: 10

INFERENCE:
  INFERENCE_NAME: InferenceChaffVideoTRT
  GENERATOR: GeneratorVideo
  INFERENCE_CSV_FILE: 
  INFERENCE_DATA_DIR:
  VIDEO_PATH: s3://zoomlion-sample/zoomlion-hopper-1/barn_video1.avi
  NUM_FRAMES: 200
  #VIDEO_PATH: s3://zoomlion-prod-data/zoomlion-s3-china-data/QingHai_Harvest_Data/2019-09-08/avi/elevator_cam/
  SPLIT: split #Column name in the csv file
  SPLIT_VAL: valid #Column content in the csv file
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label
  NUM_PROCESS_IMAGE: 150
  PRED_IMAGE_DIR: pred_image
  MAXIMIZING_BUFFER_LENGTH: 1
  OUTPUT_FPS: 5
  MAKE_PLOTS: false
  PB_FILE_PATH: s3://zoomlion-sample/tmp_unet_chaff_hopper_model/frozen_model.pb
  TRT_ENGINE_PATH: ~/zoomlion-sample/tmp_unet_chaff_hopper_model/frozen_model.engine
  CREATE_ENGINE: False
  FP16_MODE: False
  INPUT_NAME: data
  OUTPUT_NAME: sigmoid/Sigmoid

LOCAL_OVERRIDE:
  DIR_OUT: ./out
  DATA_DIR: null

GRU:
  JOB_NAME: chaff_hopper_data_v04
  PROJECT_NAME: wheat_yield_chaff
  INSTANCE_TYPE: p3.2xlarge
  TIMEOUT: 96
