RUN_ENV: local #{aws, local}
BATCH_SIZE: 16
DATA_CSV: data/train_vibration0606.csv
LEARNING_RATE: 0.00001
EPOCHS: 700
STEPS_PER_EPOCH: -1
PRETRAINED: true
DROPOUT: 0.25
NUM_CLASSES: 3
CHANNEL_LIST: [512, 256, 128]
ACTIVATION: relu
RESIZE: [300, 300]

LOCAL_PARA:
  DIR_OUT: ./out
  DATA_DIR: wheat-vibration-0606

AWS_PARA:
  DIR_OUT: /workspace/output/
  DATA_DIR: s3://zoomlion-sample/archive/wheat-vibration-0606/

DATA_GENERATOR:
  OUTPUT_SHAPE: [null, null]
  OUTPUT_IMAGE_CHANNELS: 3
  OUTPUT_IMAGE_TYPE: uint8
  DROP_REMAINDER: false
  CACHE_DIR: cache
  NUM_PARALLEL_CALLS: 4
  REPEAT: true

TRANSFORM:
  RESIZE: [300, 300]
  RANDOMCROP: [388, 388]

TRAINING_DATA_CSV_SCHEMA:
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: segmentation_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label
  SPLIT: split
  SPLIT_TRAIN_VAL: train
  SPLIT_VALID_VAL: valid

EXPERIMENT:
  EXPERIMENT_NAME: ExperimentClassification
  MODEL_NAME: ModelResnetClassification
  TRAIN_TRANSFORM: TransformSimpleClassification
  TRAIN_GENERATOR: GeneratorClassificationVanilla
  VALID_TRANSFORM: # If empty, use TRAIN_TRANSFORM
  VALID_GENERATOR: # If empty, use TRAIN_GENERATOR
