RUN_ENV: local #{aws, local}
RUN_MODE: train #{train, inference}
BATCH_SIZE: 16
LEARNING_RATE: 0.00001
EPOCHS: 100
TRAIN_STEPS_PER_EPOCH: -1
VALID_STEPS_PER_EPOCH: -1
PRETRAINED: true  #ignored forModelResnetClassificationYield
DROPOUT: 0.5
NUM_CLASSES: 3
CHANNEL_LIST: [256,128]
DENSE_LIST: [256, 128]  #ignored for ModelResnetClassification
ACTIVATION: relu
LOAD_MODEL: false  #if true, Load_Model_Directory must be specified too
LOAD_MODEL_DIRECTORY: null #can be s3 path, hdf5 file format
DIR_OUT: /workspace/output/
DATA_DIR: s3://landing-client-zoomlion/yield_classification/yield_hopper/


DATA_GENERATOR:
  OUTPUT_SHAPE: [null, null]
  OUTPUT_IMAGE_CHANNELS: 3  #Set to 3 if USE_SPLICER: false, set to 6 if true
  OUTPUT_IMAGE_TYPE: float32
  DROP_REMAINDER: false
  CACHE_DIR: cache
  NUM_PARALLEL_CALLS: 4
  REPEAT: true

TRANSFORM:
  RESIZE: [300, 300]
  BUFFER_SIZE: 60
  USE_SPLICER: false


TRAINING_DATA_INFO:
  TRAIN_CSV_FILE: s3://landing-client-zoomlion/yield_classification/yield_hopper/train.csv
  VALID_CSV_FILE: s3://landing-client-zoomlion/yield_classification/yield_hopper/train.csv
  SPLIT: split
  SPLIT_TRAIN_VAL: train
  SPLIT_VALID_VAL: valid
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label

EXPERIMENT:
  EXPERIMENT_NAME: ExperimentClassification
  MODEL_NAME: ModelResnetClassification  #Set to ModelResnetClassification if USE_SPLICER: false
  TRAIN_TRANSFORM: TransformClassificationYield 
  TRAIN_GENERATOR: GeneratorClassification
  VALID_TRANSFORM: # If empty, use TRAIN_TRANSFORM
  VALID_GENERATOR: # If empty, use TRAIN_GENERATOR


LOCAL_OVERRIDE:
  DIR_OUT: ./out
  DATA_DIR:


GRU:
  JOB_NAME: wheat_yield_delta_classification
  PROJECT_NAME: wheat_yield_delta
  INSTANCE_TYPE: p3.2xlarge
  TIMEOUT: 8