RUN_ENV: aws #{aws, local}
RUN_MODE: inference #{train, inference}
BATCH_SIZE: 4
LEARNING_RATE: 0.0001
EPOCHS: 300
TRAIN_STEPS_PER_EPOCH: -1
VALID_STEPS_PER_EPOCH: -1
NUM_CLASSES: 2
LOAD_MODEL: True  #if true, Load_Model_Directory must be specified too
LOAD_MODEL_DIRECTORY: s3://landing-ml-job-runs/wheat_yield/botan/wheat_lodging_segmentation/run_006/checkpoints/epoch_0138/cp.hdf5
DIR_OUT: /workspace/output/  #directory on the ec2 host, to save output files from code
DATA_DIR: s3://zoomlion-prod-data/harvester/wheat-lodging/segmentation/data-v0.3/


DATA_GENERATOR:
  OUTPUT_SHAPE: [512, 512]
  OUTPUT_IMAGE_CHANNELS: 3
  OUTPUT_IMAGE_TYPE: float32
  DROP_REMAINDER: false
  CACHE_DIR: cache
  NUM_PARALLEL_CALLS: 4
  REPEAT: true

TRANSFORM:
  RESIZE: [512, 512]

TRAINING_DATA_INFO:
  TRAIN_CSV_FILE: s3://zoomlion-prod-data/harvester/wheat-lodging/segmentation/data-v0.3/train.csv
  VALID_CSV_FILE: s3://zoomlion-prod-data/harvester/wheat-lodging/segmentation/data-v0.3/train.csv
  SPLIT: split
  SPLIT_TRAIN_VAL: train
  SPLIT_VALID_VAL: valid
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label


MODEL:
  LAYER_SIZE: 64
  LAYER_COUNT: 3
  BACKBONE: mobilenet-v2
  IS_BACKBONE_TRAINABLE: true
  MODEL_DIRECTORY: out
  CHECKPOINT_DIRECTORY: checkpoint
  LOG_DIRECTORY: log


EXPERIMENT:
  EXPERIMENT_NAME: ExperimentSegmentationUnet
  MODEL_NAME: ModelUnetSegmentation
  TRAIN_TRANSFORM: TransformSegmentation
  TRAIN_GENERATOR: GeneratorVideo
  VALID_TRANSFORM: # If empty, use TRAIN_TRANSFORM
  VALID_GENERATOR: # If empty, use TRAIN_GENERATOR


INFERENCE:
  INFERENCE_NAME: InferenceLodgingVideo
  #FIXME: May want to consider move INFERENCE_CSV_FILE and INFERENCE_DATA_DIR out of INFERENCE. We may load model for continuous training.
  INFERENCE_CSV_FILE: inference-data/data-v0.2/train.csv
  INFERENCE_DATA_DIR: inference-data/data-v0.2/
  VIDEO_PATH: s3://zoomlion-sample/wheat-lodging/lodgingwheat/106APPLE/IMG_6989.MOV
  SPLIT: split #Column name in the csv file
  SPLIT_VAL: valid #Column content in the csv file
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label
  NUM_PROCESS_IMAGE: -1
  PRED_IMAGE_DIR: pred_image


LOCAL_OVERRIDE:
  DIR_OUT: ./out
  DATA_DIR: