RUN_ENV: aws #{aws, local}
RUN_MODE: train #{train, inference}
BATCH_SIZE: 4
LEARNING_RATE: 0.0001
EPOCHS: 300
TRAIN_STEPS_PER_EPOCH: -1
VALID_STEPS_PER_EPOCH: -1
NUM_CLASSES: 2
LOAD_MODEL: false  #if true, Load_Model_Directory must be specified too
LOAD_MODEL_DIRECTORY:
DIR_OUT: /workspace/output/  #directory on the ec2 host, to save output files from code
DATA_DIR: s3://zoomlion-prod-data/harvester/wheat-lodging/segmentation/data-v0.3/


DATA_GENERATOR:
  OUTPUT_SHAPE: [512, 512]
  OUTPUT_IMAGE_CHANNELS: 3
  OUTPUT_IMAGE_TYPE: float32
  DROP_REMAINDER: false
  CACHE_DIR: cache
  NUM_PARALLEL_CALLS: 4
  REPEAT: true

TRANSFORM:
  RESIZE: [512, 512]

TRAINING_DATA_INFO:
  TRAIN_CSV_FILE: s3://zoomlion-prod-data/harvester/wheat-lodging/segmentation/data-v0.3/train.csv
  VALID_CSV_FILE: s3://zoomlion-prod-data/harvester/wheat-lodging/segmentation/data-v0.3/train.csv
  SPLIT: split
  SPLIT_TRAIN_VAL: train
  SPLIT_VALID_VAL: valid
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label


MODEL:
  LAYER_SIZE: 64
  LAYER_COUNT: 5
  BACKBONE: efficientnetb0
  IS_BACKBONE_TRAINABLE: true
  MODEL_DIRECTORY: out
  CHECKPOINT_DIRECTORY: checkpoint
  LOG_DIRECTORY: log


EXPERIMENT:
  EXPERIMENT_NAME: ExperimentSegmentationUnet
  MODEL_NAME: ModelUnetSegmentation
  TRAIN_TRANSFORM: TransformSegmentation
  TRAIN_GENERATOR: GeneratorSegmentation
  VALID_TRANSFORM: # If empty, use TRAIN_TRANSFORM
  VALID_GENERATOR: # If empty, use TRAIN_GENERATOR
  NUM_PLOTS: 10


INFERENCE:
  INFERENCE_NAME: InferenceLodgingVideo
  #FIXME: May want to consider move INFERENCE_CSV_FILE and INFERENCE_DATA_DIR out of INFERENCE. We may load model for continuous training.
  #INFERENCE_CSV_FILE: s3://zoomlion-prod-data/harvester/wheat-lodging/segmentation/data-v0.3/train.csv
  #INFERENCE_DATA_DIR: s3://zoomlion-prod-data/harvester/wheat-lodging/segmentation/data-v0.3/
  INFERENCE_CSV_FILE: s3://zoomlion-sample/wheat-lodging/lodgingwheat/train_raw_sort.csv
  INFERENCE_DATA_DIR: s3://zoomlion-sample/wheat-lodging/lodgingwheat/
  #LOAD_MODEL_PATH: wheat_lodging_segmentation_run/run_006/checkpoints/epoch_0221/cp.hdf5
  VIDEO_PATH: s3://zoomlion-sample/wheat-lodging/lodgingwheat/106APPLE/IMG_6989.MOV
  SPLIT: split #Column name in the csv file
  #SPLIT_VAL: valid #Column content in the csv file
  #SPLIT_VAL: train #Column content in the csv file
  SPLIT_VAL: raw
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label
  NUM_PROCESS_IMAGE: 30000
  PRED_IMAGE_DIR: pred_image


LOCAL_OVERRIDE:
  DIR_OUT: ./out
  DATA_DIR:

GRU:
  JOB_NAME: test_lodging_seg
  PROJECT_NAME: wheat_yield_lodging
  INSTANCE_TYPE: p3.2xlarge
  TIMEOUT: 96