RUN_ENV: local #{aws, local}
RUN_MODE: train #{train, inference}
BATCH_SIZE: 4
LEARNING_RATE: 0.0001
EPOCHS: 1000
TRAIN_STEPS_PER_EPOCH: -1
VALID_STEPS_PER_EPOCH: -1
NUM_CLASSES: 2
LOAD_MODEL: false  #if true, Load_Model_Directory must be specified too
LOAD_MODEL_DIRECTORY: s3://landing-ml-job-runs/wheat_yield/trosenflanz/wheat_chaff_segmentation/run_038/checkpoints/epoch_0017/cp.hdf5 #can be s3 path, hdf5 file format
DIR_OUT: /workspace/output/
DATA_DIR: s3://zoomlion-prod-data/harvester/chaff-content/segmentation/data-v0.3/


DATA_GENERATOR:
  OUTPUT_SHAPE: [512, 512]
  OUTPUT_IMAGE_CHANNELS: 3
  OUTPUT_IMAGE_TYPE: float32
  DROP_REMAINDER: false
  CACHE_DIR: cache
  NUM_PARALLEL_CALLS: 4
  REPEAT: true

TRANSFORM:
  RESIZE: [512, 512]

TRAINING_DATA_INFO:
  TRAIN_CSV_FILE: s3://zoomlion-prod-data/harvester/chaff-content/segmentation/data-v0.3/train.csv
  VALID_CSV_FILE: s3://zoomlion-prod-data/harvester/chaff-content/segmentation/data-v0.3/train.csv
  SPLIT: split
  SPLIT_TRAIN_VAL: train
  SPLIT_VALID_VAL: valid
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label


MODEL:
  LAYER_SIZE: 64
  LAYER_COUNT: 3
  BACKBONE: mobilenet-v2
  IS_BACKBONE_TRAINABLE: true

EXPERIMENT:
  EXPERIMENT_NAME: ExperimentSegmentationTF2Unet
  MODEL_NAME: ModelTF2UnetSegmentation
  TRAIN_TRANSFORM: TransformSegmentation
  TRAIN_GENERATOR: GeneratorSegmentationTF2Unet
  VALID_TRANSFORM: # If empty, use TRAIN_TRANSFORM
  VALID_GENERATOR: # If empty, use TRAIN_GENERATOR

LOCAL_OVERRIDE:
  DIR_OUT: ./out
  DATA_DIR: