RUN_ENV: aws #{aws, local}
RUN_MODE: train #{train, inference}
BATCH_SIZE: 4
LEARNING_RATE: 0.0001
EPOCHS: 1000
TRAIN_STEPS_PER_EPOCH: -1
VALID_STEPS_PER_EPOCH: -1
NUM_CLASSES: 2
LOAD_MODEL: false  #if true, Load_Model_Directory must be specified too
LOAD_MODEL_DIRECTORY: s3://landing-ml-job-runs/wheat_yield/botan/wheat_breakage_segmentation/run_001/checkpoints/epoch_0999/
DIR_OUT: /workspace/output/  #directory on the ec2 host, to save output files from code
DATA_DIR: s3://zoomlion-prod-data/harvester/wheat-breakage/bounding-box/data-v0.1/


DATA_GENERATOR:
  OUTPUT_SHAPE: [512, 512]
  OUTPUT_IMAGE_CHANNELS: 3
  OUTPUT_IMAGE_TYPE: float32
  DROP_REMAINDER: false
  CACHE_DIR: cache
  NUM_PARALLEL_CALLS: 4
  REPEAT: true

TRANSFORM:
  RESIZE: [512, 512]

TRAINING_DATA_INFO:
  TRAIN_CSV_FILE: s3://zoomlion-prod-data/harvester/wheat-breakage/bounding-box/data-v0.1/train.csv
  VALID_CSV_FILE: s3://zoomlion-prod-data/harvester/wheat-breakage/bounding-box/data-v0.1/train.csv
  SPLIT: split
  SPLIT_TRAIN_VAL: train
  SPLIT_VALID_VAL: valid
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  BBOX_LABEL_PATH: bbox_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label
  

MODEL:
  LAYER_SIZE: 64
  LAYER_COUNT: 3
  BACKBONE: mobilenet-v2
  IS_BACKBONE_TRAINABLE: true
  MODEL_DIRECTORY: out
  CHECKPOINT_DIRECTORY: checkpoint
  LOG_DIRECTORY: log
  ANCHORPARAMS : 
    sizes : [16, 32, 64, 128, 256]
    strides : [8, 16, 32, 64, 128] 
    ratios : [0.5, 1, 2]
    scales :  [1, 1.2599, 1.5874]



EXPERIMENT:
  EXPERIMENT_NAME: ExperimentBbox
  MODEL_NAME: ModelRetinaNet
  TRAIN_TRANSFORM: TransformBbox
  TRAIN_GENERATOR: GeneratorRetinaNet
  VALID_TRANSFORM: # If empty, use TRAIN_TRANSFORM
  VALID_GENERATOR: # If empty, use TRAIN_GENERATOR

INFERENCE:
  INFERENCE_NAME: InferenceLodging
  #FIXME: May want to consider move INFERENCE_CSV_FILE and INFERENCE_DATA_DIR out of INFERENCE. We may load model for continuous training.
  INFERENCE_CSV_FILE: s3://zoomlion-prod-data/harvester/wheat-breakage/bounding-box/seg-data-v0.2/seg_train.csv
  INFERENCE_DATA_DIR: s3://zoomlion-prod-data/harvester/wheat-breakage/bounding-box/seg-data-v0.2/
  VIDEO_PATH:
  SPLIT: split #Column name in the csv file
  SPLIT_VAL: valid
  SEPARATOR: ','
  IMAGE_PATH: image_path
  SEGMENTATION_PATH: seg_label_path
  LABEL_NAME: label_name
  IMAGE_LEVEL_LABEL: image_level_label
  NUM_PROCESS_IMAGE: 30000
  PRED_IMAGE_DIR: pred_image


LOCAL_OVERRIDE:
  DIR_OUT: ./out
  DATA_DIR:

GRU:
  JOB_NAME: wheat_breakage_segmentation
  PROJECT_NAME: wheat_yield_breakage
  INSTANCE_TYPE: p3.2xlarge
  TIMEOUT: 96
