RUN_ENV: local #{aws, local}
RUN_MODE: train #{train, inference}
BATCH_SIZE: 4
LEARNING_RATE: 0.0001
EPOCHS: 5
TRAIN_STEPS_PER_EPOCH: -1
VALID_STEPS_PER_EPOCH: -1
NUM_CLASSES: 2
LOAD_MODEL: false  #if true, Load_Model_Directory must be specified too
LOAD_MODEL_DIRECTORY:
DIR_OUT: /workspace/output/  #directory on the ec2 host, to save output files from code
DATA_DIR: #unused


DATA_GENERATOR:
  OUTPUT_SHAPE: [128, 128]
  OUTPUT_IMAGE_CHANNELS: 3
  OUTPUT_IMAGE_TYPE: float32
  DROP_REMAINDER: false
  CACHE_DIR: cache
  NUM_PARALLEL_CALLS: 4
  REPEAT: true

TRANSFORM:
  RESIZE: [128, 128]

TRAINING_DATA_INFO:
  TRAIN_CSV_FILE: s3://zoomlion-dev-data/sprayer/weed-bbox-seg-v0.1/train.csv
  VALID_CSV_FILE: s3://zoomlion-dev-data/sprayer/weed-bbox-seg-v0.1/train.csv
  SPLIT: split
  SPLIT_TRAIN_VAL: train
  SPLIT_VALID_VAL: valid
  SEPARATOR: ','
  IMAGE_PATH: image
  SEGMENTATION_PATH: seg_label
  LABEL_NAME: #unused
  IMAGE_LEVEL_LABEL: #unused

INFERENCE:
  INFERENCE_NAME: InferenceSprayerCornVideo
  INFERENCE_CSV_FILE:
  INFERENCE_DATA_DIR:
  GENERATOR: GeneratorVideo
  VIDEO_PATH: s3://zoomlion-dev-data/sprayer/sprayer-corn_2019-08-15-164430.avi
  NUM_PROCESS_IMAGE: -1
  PRED_IMAGE_DIR: pred_image
  SPLIT:
  SPLIT_VAL:
  SEPARATOR:
  IMAGE_PATH:
  SEGMENTATION_PATH:
  LABEL_NAME:
  IMAGE_LEVEL_LABEL:

MODEL:
  LAYER_SIZE: 64
  LAYER_COUNT: 3
  BACKBONE: mobilenetv2
  IS_BACKBONE_TRAINABLE: true

EXPERIMENT:
  EXPERIMENT_NAME: ExperimentSegmentationUnet
  MODEL_NAME: ModelUnetSegmentation
  TRAIN_TRANSFORM: TransformSegmentation
  TRAIN_GENERATOR: GeneratorSegmentation
  VALID_TRANSFORM: # If empty, use TRAIN_TRANSFORM
  VALID_GENERATOR: # If empty, use TRAIN_GENERATOR
  NUM_PLOTS: 10

LOCAL_OVERRIDE:
  DIR_OUT: ./out
  DATA_DIR: #unused

GRU:
  JOB_NAME: sprayer_corn_segmentation
  PROJECT_NAME: sprayer_corn
  INSTANCE_TYPE: p3.2xlarge
  TIMEOUT: 96